name: Rully Pratama
url: https://rullypratama.com

links:
  linkedin: https://www.linkedin.com/in/rullypratama

personal:
  name: Rully Pratama
  email: hello@rullypratama.com
  account: rully

permalink: /:year/:month/:slug:output_ext

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - env
  - _posts_todo
  - redirects.json
  - requirements.txt
  - purgecss.config.js
  - package.json
  - package-lock.json
  - _checks
  - .clang-format

include:
  - .well-known

destination: _deploy

highlighter: rouge

# TODO: inherit some of these from site.links

header:
  links:
    - icon: list
      url: /archive.html
      title: Blog archive
    - icon: camera
      url: https://photos.rullypratama.com
      title: My photo gallery
    - icon: linkedin
      url: https://www.linkedin.com/in/rullypratama
      title: My LinkedIn profile
    - icon: resume
      url: /assets/resume/resume.html
      title: My Resume

plugins:
  - jekyll-sitemap
  - jekyll-purgecss
  - jekyll-minifier
  - jekyll-postfiles

# Disable smart quotes
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

jekyll-minifier:
  remove_intertag_spaces: true
  remove_quotes: true
  simple_doctype: true
  simple_boolean_attributes: true
  compress_js_templates: true
  uglifier_args:
    harmony: true

# Google Analytics
google_analytics: G-1NNK8DC7FT